auth:
  adminUser: root
  adminPassword: root

## to serve on existing domains subpath: https://my-keycloak.com/here-is-keycloak/
httpRelativePath: /here-is-keycloak/
ingress:
  enabled: true
  hostname: my-keycloak.com
  hostnameStrict: true
  pathType: Prefix
  ingressClassName: nginx
  tls: true
  extraTls:
  - hosts:
    - my-keycloak.com
    secretName: runai-cluster-domain-tls-secret

logging:
  level: DEBUG

# # to serve on a separate domain: https://my-keycloak.com/
# ingress:
#   enabled: true
#   hostname: my-keycloak.com
#   hostnameStrict: true
#   ingressClassName: nginx
#   tls: true
#   extraTls:
#   - hosts:
#     - my-keycloak.com
#     secretName: runai-cluster-domain-tls-secret